# Read File CSV Dataset Training

In [1]:
import pandas as pd

dataset_tweet_emotion   = pd.read_csv('dataset/mentah/Dataset Label Emotion.csv')
dataset_keyword_banjir  = pd.read_csv('dataset/mentah/Dataset Label Keyword Banjir Sumatra.csv')
dataset_keyword_jokowi  = pd.read_csv('dataset/mentah/Dataset Label Keyword Jokowi.csv')
dataset_pilpres         = pd.read_csv('dataset/mentah/Dataset Label Pilpres 2024.csv')
dataset_ppkm            = pd.read_csv('dataset/mentah/Dataset Label PPKM.csv', sep=None, engine='python')
dataset_label_ite       = pd.read_csv('dataset/mentah/Dataset Twitter Fix - Indonesian Sentiment Twitter Dataset Labeled (1).csv')
dataset_youtube_comment = pd.read_excel('dataset/mentah/4000 Indonesian Youtube Comments.xlsx')
dataset_sent_net_indo   = pd.read_csv('dataset/mentah/sentiment_NetizenIndonesianLangugage.csv')
dataset_review_startup  = pd.read_csv('dataset/mentah/review-startup.csv')

In [2]:
dataset_tweet_emotion

        label                                              tweet
0       anger  Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...
1       anger  Sesama cewe lho (kayaknya), harusnya bisa lebi...
2       happy  Kepingin gudeg mbarek Bu hj. Amad Foto dari go...
3       anger  Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...
4       happy  Sharing pengalaman aja, kemarin jam 18.00 bata...
...       ...                                                ...
4396     love  Tahukah kamu, bahwa saat itu papa memejamkan m...
4397     fear  Sulitnya menetapkan Calon Wapresnya Jokowi di ...
4398    anger  5. masa depannya nggak jelas. lha iya, gimana ...
4399    happy  [USERNAME] dulu beneran ada mahasiswa Teknik U...
4400  sadness  Ya Allah, hanya Engkau yang mengetahui rasa sa...

[4401 rows x 2 columns]

In [3]:
dataset_keyword_banjir

                                                  chat     rate
0    Ya Allah...mesjidnya msh bagus & lgsg bisa dim...  Positif
1    SUBHANALLAH... Sungguh beruntunglah orang2 yg ...  Positif
2    Hulu nya juga harus di perbaiki... Kalo hujan ...   Netral
3    Semoga semua rumah korban bisa dibersihkan jug...  Negatif
4    Tahun 2006, pemerintah sampai membentuk BRR Ac...  Negatif
..                                                 ...      ...
280  Kali Cengkareng dahulu setiap musim penghujan ...   Netral
281  prabowo Jika sebagai presiden, sudah saya teta...  Positif
282  Berarti selama ini ada yang ditutup-tutupi ya ...   Netral
283  Dan ada yg jlnnya  masih gontai ketika turun d...   Netral
284                 Buka akses utk bantuan asing masuk   Netral

[285 rows x 2 columns]

In [4]:
dataset_keyword_jokowi

      Unnamed: 0                                               text    Label
0              0  rt @megatop99: @conannkri @ccicpolri @mohmahfu...  positif
1              1  @jokowi harga2 pd naik gaji aparat negara gk n...  negatif
2              2  xx : kalian coba mengusir yang mau membersihka...  negatif
3              3  @jokowi haturnuhun bapak presiden @jokowi tela...   netral
4              4  @rifanrobani @catatan_ali7 @erickthohir @jokow...   netral
...          ...                                                ...      ...
1001        1001  Memang hebat orang pilihan pak @jokowi ini, lu...  positif
1002        1002  Kunjungan Kehormatan Presiden @jokowi dan Ibu ...  positif
1003        1003  Berbagai upaya dilakukan Indonesia untuk melak...  positif
1004        1004  Sebagai tindak lanjut perintah Presiden @jokow...  positif
1005        1005  Dengan memanfaat teknologi, jangan heran kalau...  positif

[1006 rows x 3 columns]

In [5]:
dataset_pilpres

,Text_Eng,Text_Ind,label
0,anies president info,informasi presiden anies,Positive
1,gerindra party politician sandiaga uno answers...,Politisi Partai Gerindra Sandaga Uno menjawab ...,Positive
2,"mr. anies continued, we will guard him until h...","Tuan Anies melanjutkan, kami akan menjaganya s...",Positive
3,may allah swt save the nation and state of the...,Semoga Allah SWT menyelamatkan bangsa dan nega...,Positive
4,"poor chotimah, uncle anies, that's why my fami...","Kasihan Chotimah, Paman Anies, itulah sebabnya...",Positive
...,...,...,...
29678,"sir, if the community always goes down, it wil...","Pak, jika komunitas selalu merosot, akan lebih...",Positive
29679,"young prabowo is really cool, bismillah sir, g...","Prabowo muda sungguh keren, bismillah Pak, ins...",Positive
29680,"basically, prabowo is great and was chosen as ...","Pada dasarnya, Prabowo hebat dan terpilih seba...",Positive
29681,optimistic about being the best figure in the ...,Bersikap optimistis menjadi tokoh terbaik dala...,Positive
29682,"the best presidential candidate, god willing, ...","Calon presiden terbaik, insya Allah, Prabowo",Positive

In [6]:
dataset_ppkm

,Date,User,Tweet,sentiment
0,2022-03-31 14:32:04+00:00,pikobar_jabar,Ketahui informasi pembagian #PPKM di wilayah J...,1
1,2022-03-31 09:26:00+00:00,inewsdotid,Tempat Ibadah di Wilayah PPKM Level 1 Boleh Be...,1
2,2022-03-31 05:02:34+00:00,vdvc_talk,"Juru bicara Satgas Covid-19, Wiku Adisasmito m...",1
3,2022-03-30 14:23:10+00:00,pikobar_jabar,Ketahui informasi pembagian #PPKM di wilayah J...,1
4,2022-03-30 11:28:57+00:00,tvOneNews,Kementerian Agama menerbitkan Surat Edaran Nom...,1
...,...,...,...,...
23639,2020-06-26 18:34:56+00:00,bananabluff,noelle loses a bet to akarsha and it somehow e...,1
23640,2020-06-19 15:14:07+00:00,Auqroix,they call her... weekeeshee...\n#butterflysoup...,1
23641,2020-06-18 23:45:26+00:00,Auqroix,"put out what you wanna see more of, amirite ga...",1
23642,2020-06-15 23:17:22+00:00,Auqroix,"i don't need anybody, i'm fine here on my own\...",1
23643,2020-05-06 04:34:13+00:00,nindiiayudya,"Selamat Siang sahabat online, nih aku sedikit ...",0

In [7]:
dataset_label_ite

       sentimen                                              Tweet
0           0.0  barusan liat tulisan di belakang truk rela inj...
1           0.0  her itu lho miss kevin sama keven rebutan gimb...
2           0.0    iya rep gatau aku masih kelas 4 sd ehh di block
3           0.0    aku mohon tepatilah janjimu penantiancintaeps19
4           0.0  bukan beria nk kahwin sbb gatal celah kangkang...
...         ...                                                ...
12642       6.0  Jangan dibahas dong, udah paham aja kan di kau...
12643       6.0  di agama lo nyembah nya siapa sih? masa Tuhan ...
12644       6.0  Katanya demi kemanusiaan, kemanusiaan milik ma...
12645       6.0         Orang timur kurang pintar dari orang barat
12646       6.0  Penistaan agama, Yesus Tuhan kok disalib sih k...

[12647 rows x 2 columns]

In [8]:
dataset_youtube_comment

,video_id,author,comment,label,Unnamed: 4
0,g_fkq6WHcOs,@DesiCahaya-c7r,Gambar kebaretnya boongan ternyata,0.0,0 = negatif
1,g_fkq6WHcOs,@CelineElviraNatalia,"Buat pemakai biasa sama saja iphone 16 promax,...",0.0,1 = netral
2,g_fkq6WHcOs,@borisdominggo,Case “poco&quot; 😂,1.0,2 = positif
3,g_fkq6WHcOs,@noname-jb4rz,Kaum miFans dan kaum munafik iri dengki lg kum...,0.0,NaN
4,g_fkq6WHcOs,@SIAPA-e8b,Saya mah nunggu S26 Ultra aja,0.0,NaN
...,...,...,...,...,...
4197,9-poYwCZxDQ,@ach.fahrurrozi,Waw amazing,NaN,NaN
4198,9-poYwCZxDQ,@muhammadauliarifan9635,halo banh,NaN,NaN
4199,9-poYwCZxDQ,@rizkiokta3404,pagi pagi bener nii,NaN,NaN
4200,9-poYwCZxDQ,@musthofa7104,Wihh,NaN,NaN
4201,9-poYwCZxDQ,@Sebastianverstappen,Ke - 5 nih,NaN,NaN

In [9]:
dataset_sent_net_indo

,product_name,review_text,sentiment
0,Basic Online Course Learning (BOCL),"Materinya goks abis, auto paham! Instrukturnya...",2.0
1,Premium Online Learning (POL),"Platformnya anjay, interaktif banget, jadi gak...",2.0
2,Private Online Course Learning (POCL),"Mentornya pro player, ngajarnya santuy tapi ng...",2.0
3,Onsite Course Learning (OCL),"Sumpah, ini kursus paling oke! Ilmunya kepake ...",2.0
4,Private Course Onsite Learning (PCOL),Sertifikatnya nampol buat naikin CV. Vibes bel...,2.0
...,...,...,...
2189,Private Course Onsite Learning (PCOL),"Sertifikatnya dapet, tapi impact-nya belum ker...",1.0
2190,Basic Online Course Learning (BOCL),"Harganya sebanding sama ilmunya. Mantap jiwa, ...",2.0
2191,Premium Online Learning (POL),"CS-nya ampas banget, slow respon, gak solutif....",0.0
2192,Private Online Course Learning (POCL),"Yaah, sesuai harga lah ya. Gak jelek-jelek ama...",1.0
2193,Onsite Course Learning (OCL),Kualitasnya jua,NaN

In [10]:
dataset_review_startup

           label                                              Tweet
0       negative  Harga harga di Blibli cenderung di atas orange...
1       negative  Platform e-commerce yang menurut saya belum pa...
2       negative  Sudah setahuan belakang ini pelayanan pengirim...
3       positive  Pengen mencoba berbelanja tapi gak jadi karena...
4       negative  Tidak jadi gw rating bintang 5 . Applikasi pen...
...          ...                                                ...
841659  negative                                                  👻
841660  negative                                           😈😈😈😈😈😈😈😈
841661  negative                                          👍👍👍👍👍👍👍👍👍
841662  negative                                                 😊😊
841663  negative                                         First?????

[841664 rows x 2 columns]

# 1. Integration Data File Emotion Tweet to Sentiment Tweet

In [11]:
dataset_tweet_emotion

        label                                              tweet
0       anger  Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...
1       anger  Sesama cewe lho (kayaknya), harusnya bisa lebi...
2       happy  Kepingin gudeg mbarek Bu hj. Amad Foto dari go...
3       anger  Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...
4       happy  Sharing pengalaman aja, kemarin jam 18.00 bata...
...       ...                                                ...
4396     love  Tahukah kamu, bahwa saat itu papa memejamkan m...
4397     fear  Sulitnya menetapkan Calon Wapresnya Jokowi di ...
4398    anger  5. masa depannya nggak jelas. lha iya, gimana ...
4399    happy  [USERNAME] dulu beneran ada mahasiswa Teknik U...
4400  sadness  Ya Allah, hanya Engkau yang mengetahui rasa sa...

[4401 rows x 2 columns]

In [12]:
# rename column

dataset_tweet_emotion = dataset_tweet_emotion[['tweet','label']].rename(columns={'tweet':'Tweet'})
dataset_tweet_emotion

                                                  Tweet    label
0     Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...    anger
1     Sesama cewe lho (kayaknya), harusnya bisa lebi...    anger
2     Kepingin gudeg mbarek Bu hj. Amad Foto dari go...    happy
3     Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...    anger
4     Sharing pengalaman aja, kemarin jam 18.00 bata...    happy
...                                                 ...      ...
4396  Tahukah kamu, bahwa saat itu papa memejamkan m...     love
4397  Sulitnya menetapkan Calon Wapresnya Jokowi di ...     fear
4398  5. masa depannya nggak jelas. lha iya, gimana ...    anger
4399  [USERNAME] dulu beneran ada mahasiswa Teknik U...    happy
4400  Ya Allah, hanya Engkau yang mengetahui rasa sa...  sadness

[4401 rows x 2 columns]

In [13]:
# mapping emotion to sentiment

emotion_to_sentiment = {
    'happy': 'positive',
    'love': 'positive',
    'anger': 'negative',
    'sadness': 'negative',
    'fear': 'negative'
}

# change label emotion to sentiment
dataset_tweet_emotion['label'] = dataset_tweet_emotion['label'].map(emotion_to_sentiment)
dataset_tweet_emotion

                                                  Tweet     label
0     Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...  negative
1     Sesama cewe lho (kayaknya), harusnya bisa lebi...  negative
2     Kepingin gudeg mbarek Bu hj. Amad Foto dari go...  positive
3     Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...  negative
4     Sharing pengalaman aja, kemarin jam 18.00 bata...  positive
...                                                 ...       ...
4396  Tahukah kamu, bahwa saat itu papa memejamkan m...  positive
4397  Sulitnya menetapkan Calon Wapresnya Jokowi di ...  negative
4398  5. masa depannya nggak jelas. lha iya, gimana ...  negative
4399  [USERNAME] dulu beneran ada mahasiswa Teknik U...  positive
4400  Ya Allah, hanya Engkau yang mengetahui rasa sa...  negative

[4401 rows x 2 columns]

# 2. Integration Data File Tweet Banjir Sumatra

In [14]:
dataset_keyword_banjir

                                                  chat     rate
0    Ya Allah...mesjidnya msh bagus & lgsg bisa dim...  Positif
1    SUBHANALLAH... Sungguh beruntunglah orang2 yg ...  Positif
2    Hulu nya juga harus di perbaiki... Kalo hujan ...   Netral
3    Semoga semua rumah korban bisa dibersihkan jug...  Negatif
4    Tahun 2006, pemerintah sampai membentuk BRR Ac...  Negatif
..                                                 ...      ...
280  Kali Cengkareng dahulu setiap musim penghujan ...   Netral
281  prabowo Jika sebagai presiden, sudah saya teta...  Positif
282  Berarti selama ini ada yang ditutup-tutupi ya ...   Netral
283  Dan ada yg jlnnya  masih gontai ketika turun d...   Netral
284                 Buka akses utk bantuan asing masuk   Netral

[285 rows x 2 columns]

In [15]:
# rename column chat and rate

dataset_keyword_banjir = dataset_keyword_banjir[['chat','rate']].rename(columns={'chat':'Tweet',
                                                                             'rate' : 'label'})
dataset_keyword_banjir

                                                 Tweet    label
0    Ya Allah...mesjidnya msh bagus & lgsg bisa dim...  Positif
1    SUBHANALLAH... Sungguh beruntunglah orang2 yg ...  Positif
2    Hulu nya juga harus di perbaiki... Kalo hujan ...   Netral
3    Semoga semua rumah korban bisa dibersihkan jug...  Negatif
4    Tahun 2006, pemerintah sampai membentuk BRR Ac...  Negatif
..                                                 ...      ...
280  Kali Cengkareng dahulu setiap musim penghujan ...   Netral
281  prabowo Jika sebagai presiden, sudah saya teta...  Positif
282  Berarti selama ini ada yang ditutup-tutupi ya ...   Netral
283  Dan ada yg jlnnya  masih gontai ketika turun d...   Netral
284                 Buka akses utk bantuan asing masuk   Netral

[285 rows x 2 columns]

In [16]:
# mapping lowercase label

rename_lowecase_label = {
    'Positif': 'positive',
    'Netral': 'neutral',
    'Negatif': 'negative',
}

# rename lowercase label
dataset_keyword_banjir['label'] = dataset_keyword_banjir['label'].map(rename_lowecase_label)
dataset_keyword_banjir

                                                 Tweet     label
0    Ya Allah...mesjidnya msh bagus & lgsg bisa dim...  positive
1    SUBHANALLAH... Sungguh beruntunglah orang2 yg ...  positive
2    Hulu nya juga harus di perbaiki... Kalo hujan ...   neutral
3    Semoga semua rumah korban bisa dibersihkan jug...  negative
4    Tahun 2006, pemerintah sampai membentuk BRR Ac...  negative
..                                                 ...       ...
280  Kali Cengkareng dahulu setiap musim penghujan ...   neutral
281  prabowo Jika sebagai presiden, sudah saya teta...  positive
282  Berarti selama ini ada yang ditutup-tutupi ya ...   neutral
283  Dan ada yg jlnnya  masih gontai ketika turun d...   neutral
284                 Buka akses utk bantuan asing masuk   neutral

[285 rows x 2 columns]

# 3. Integration Data File Tweet Keyword Jokowi

In [17]:
dataset_keyword_jokowi

      Unnamed: 0                                               text    Label
0              0  rt @megatop99: @conannkri @ccicpolri @mohmahfu...  positif
1              1  @jokowi harga2 pd naik gaji aparat negara gk n...  negatif
2              2  xx : kalian coba mengusir yang mau membersihka...  negatif
3              3  @jokowi haturnuhun bapak presiden @jokowi tela...   netral
4              4  @rifanrobani @catatan_ali7 @erickthohir @jokow...   netral
...          ...                                                ...      ...
1001        1001  Memang hebat orang pilihan pak @jokowi ini, lu...  positif
1002        1002  Kunjungan Kehormatan Presiden @jokowi dan Ibu ...  positif
1003        1003  Berbagai upaya dilakukan Indonesia untuk melak...  positif
1004        1004  Sebagai tindak lanjut perintah Presiden @jokow...  positif
1005        1005  Dengan memanfaat teknologi, jangan heran kalau...  positif

[1006 rows x 3 columns]

In [18]:
# rename column text and label

dataset_keyword_jokowi = dataset_keyword_jokowi[['text','Label']].rename(columns={'text':'Tweet',
                                                                             'Label' : 'label'})
dataset_keyword_jokowi

                                                  Tweet    label
0     rt @megatop99: @conannkri @ccicpolri @mohmahfu...  positif
1     @jokowi harga2 pd naik gaji aparat negara gk n...  negatif
2     xx : kalian coba mengusir yang mau membersihka...  negatif
3     @jokowi haturnuhun bapak presiden @jokowi tela...   netral
4     @rifanrobani @catatan_ali7 @erickthohir @jokow...   netral
...                                                 ...      ...
1001  Memang hebat orang pilihan pak @jokowi ini, lu...  positif
1002  Kunjungan Kehormatan Presiden @jokowi dan Ibu ...  positif
1003  Berbagai upaya dilakukan Indonesia untuk melak...  positif
1004  Sebagai tindak lanjut perintah Presiden @jokow...  positif
1005  Dengan memanfaat teknologi, jangan heran kalau...  positif

[1006 rows x 2 columns]

In [19]:
# count label

dataset_keyword_jokowi['label'].value_counts()

label
positif     373
negatif     372
netral      254
negartif      2
netr          2
Negatif       1
positi        1
Name: count, dtype: int64

In [20]:
# mapping label

mapping_typo_label_dataset_keyword_jokowi = {
    'positif'       : 'positive',
    'positi'        : 'positive',
    'netral'        : 'neutral',
    'netr'          : 'neutral',
    'negatif'       : 'negative',
    'negartif'      : 'negative',
    'Negatif'       : 'negative',
}

# rename lowercase label
dataset_keyword_jokowi['label'] = dataset_keyword_jokowi['label'].map(mapping_typo_label_dataset_keyword_jokowi)
dataset_keyword_jokowi

                                                  Tweet     label
0     rt @megatop99: @conannkri @ccicpolri @mohmahfu...  positive
1     @jokowi harga2 pd naik gaji aparat negara gk n...  negative
2     xx : kalian coba mengusir yang mau membersihka...  negative
3     @jokowi haturnuhun bapak presiden @jokowi tela...   neutral
4     @rifanrobani @catatan_ali7 @erickthohir @jokow...   neutral
...                                                 ...       ...
1001  Memang hebat orang pilihan pak @jokowi ini, lu...  positive
1002  Kunjungan Kehormatan Presiden @jokowi dan Ibu ...  positive
1003  Berbagai upaya dilakukan Indonesia untuk melak...  positive
1004  Sebagai tindak lanjut perintah Presiden @jokow...  positive
1005  Dengan memanfaat teknologi, jangan heran kalau...  positive

[1006 rows x 2 columns]

In [21]:
# count label

dataset_keyword_jokowi['label'].value_counts()

label
negative    375
positive    374
neutral     256
Name: count, dtype: int64

# 4. Integration Data File Tweet Pilpres 2024

In [22]:
dataset_pilpres

,Text_Eng,Text_Ind,label
0,anies president info,informasi presiden anies,Positive
1,gerindra party politician sandiaga uno answers...,Politisi Partai Gerindra Sandaga Uno menjawab ...,Positive
2,"mr. anies continued, we will guard him until h...","Tuan Anies melanjutkan, kami akan menjaganya s...",Positive
3,may allah swt save the nation and state of the...,Semoga Allah SWT menyelamatkan bangsa dan nega...,Positive
4,"poor chotimah, uncle anies, that's why my fami...","Kasihan Chotimah, Paman Anies, itulah sebabnya...",Positive
...,...,...,...
29678,"sir, if the community always goes down, it wil...","Pak, jika komunitas selalu merosot, akan lebih...",Positive
29679,"young prabowo is really cool, bismillah sir, g...","Prabowo muda sungguh keren, bismillah Pak, ins...",Positive
29680,"basically, prabowo is great and was chosen as ...","Pada dasarnya, Prabowo hebat dan terpilih seba...",Positive
29681,optimistic about being the best figure in the ...,Bersikap optimistis menjadi tokoh terbaik dala...,Positive
29682,"the best presidential candidate, god willing, ...","Calon presiden terbaik, insya Allah, Prabowo",Positive

In [23]:
# drop coloumn Text_Eng

dataset_pilpres.drop(columns=["Text_Eng"], inplace=True)

# rename column Text_Ind to Tweet
dataset_pilpres.rename(columns={"Text_Ind": "Tweet"}, inplace=True)

dataset_pilpres

                                                   Tweet     label
0                               informasi presiden anies  Positive
1      Politisi Partai Gerindra Sandaga Uno menjawab ...  Positive
2      Tuan Anies melanjutkan, kami akan menjaganya s...  Positive
3      Semoga Allah SWT menyelamatkan bangsa dan nega...  Positive
4      Kasihan Chotimah, Paman Anies, itulah sebabnya...  Positive
...                                                  ...       ...
29678  Pak, jika komunitas selalu merosot, akan lebih...  Positive
29679  Prabowo muda sungguh keren, bismillah Pak, ins...  Positive
29680  Pada dasarnya, Prabowo hebat dan terpilih seba...  Positive
29681  Bersikap optimistis menjadi tokoh terbaik dala...  Positive
29682       Calon presiden terbaik, insya Allah, Prabowo  Positive

[29683 rows x 2 columns]

In [24]:
# count label 

label_counts_dataset_pilpres = dataset_pilpres['label'].value_counts()
label_counts_dataset_pilpres

label
Positive    21612
Negative     8068
Name: count, dtype: int64

In [25]:
# mapping label typo

mapping_typo_label_dataset_pilpres = {
    'Positive': 'positive',
    'Negative': 'negative',
}

# rename lowercase label
dataset_pilpres['label'] = dataset_pilpres['label'].map(mapping_typo_label_dataset_pilpres)
dataset_pilpres

                                                   Tweet     label
0                               informasi presiden anies  positive
1      Politisi Partai Gerindra Sandaga Uno menjawab ...  positive
2      Tuan Anies melanjutkan, kami akan menjaganya s...  positive
3      Semoga Allah SWT menyelamatkan bangsa dan nega...  positive
4      Kasihan Chotimah, Paman Anies, itulah sebabnya...  positive
...                                                  ...       ...
29678  Pak, jika komunitas selalu merosot, akan lebih...  positive
29679  Prabowo muda sungguh keren, bismillah Pak, ins...  positive
29680  Pada dasarnya, Prabowo hebat dan terpilih seba...  positive
29681  Bersikap optimistis menjadi tokoh terbaik dala...  positive
29682       Calon presiden terbaik, insya Allah, Prabowo  positive

[29683 rows x 2 columns]

In [26]:
# count label 

label_counts_dataset_pilpres = dataset_pilpres['label'].value_counts()
label_counts_dataset_pilpres

label
positive    21612
negative     8068
Name: count, dtype: int64

# 5. Integration Data File Tweet PPKM from Sentiment Label Number to Text

In [27]:
dataset_ppkm

,Date,User,Tweet,sentiment
0,2022-03-31 14:32:04+00:00,pikobar_jabar,Ketahui informasi pembagian #PPKM di wilayah J...,1
1,2022-03-31 09:26:00+00:00,inewsdotid,Tempat Ibadah di Wilayah PPKM Level 1 Boleh Be...,1
2,2022-03-31 05:02:34+00:00,vdvc_talk,"Juru bicara Satgas Covid-19, Wiku Adisasmito m...",1
3,2022-03-30 14:23:10+00:00,pikobar_jabar,Ketahui informasi pembagian #PPKM di wilayah J...,1
4,2022-03-30 11:28:57+00:00,tvOneNews,Kementerian Agama menerbitkan Surat Edaran Nom...,1
...,...,...,...,...
23639,2020-06-26 18:34:56+00:00,bananabluff,noelle loses a bet to akarsha and it somehow e...,1
23640,2020-06-19 15:14:07+00:00,Auqroix,they call her... weekeeshee...\n#butterflysoup...,1
23641,2020-06-18 23:45:26+00:00,Auqroix,"put out what you wanna see more of, amirite ga...",1
23642,2020-06-15 23:17:22+00:00,Auqroix,"i don't need anybody, i'm fine here on my own\...",1
23643,2020-05-06 04:34:13+00:00,nindiiayudya,"Selamat Siang sahabat online, nih aku sedikit ...",0

In [28]:
# drop coloumn date and user

dataset_ppkm.drop(columns=["Date", "User"], inplace=True)

# rename column sentiment to label
dataset_ppkm.rename(columns={"sentiment": "label"}, inplace=True)

dataset_ppkm

                                                   Tweet  label
0      Ketahui informasi pembagian #PPKM di wilayah J...      1
1      Tempat Ibadah di Wilayah PPKM Level 1 Boleh Be...      1
2      Juru bicara Satgas Covid-19, Wiku Adisasmito m...      1
3      Ketahui informasi pembagian #PPKM di wilayah J...      1
4      Kementerian Agama menerbitkan Surat Edaran Nom...      1
...                                                  ...    ...
23639  noelle loses a bet to akarsha and it somehow e...      1
23640  they call her... weekeeshee...\n#butterflysoup...      1
23641  put out what you wanna see more of, amirite ga...      1
23642  i don't need anybody, i'm fine here on my own\...      1
23643  Selamat Siang sahabat online, nih aku sedikit ...      0

[23644 rows x 2 columns]

In [29]:
# mapping number label sentiment to text label sentiment

number_to_sentiment = {
    0: 'positive',
    1: 'neutral',
    2: 'negative'
}

# change number label sentiment to text label sentiment

dataset_ppkm['label'] = dataset_ppkm['label'].map(number_to_sentiment)
dataset_ppkm

                                                   Tweet     label
0      Ketahui informasi pembagian #PPKM di wilayah J...   neutral
1      Tempat Ibadah di Wilayah PPKM Level 1 Boleh Be...   neutral
2      Juru bicara Satgas Covid-19, Wiku Adisasmito m...   neutral
3      Ketahui informasi pembagian #PPKM di wilayah J...   neutral
4      Kementerian Agama menerbitkan Surat Edaran Nom...   neutral
...                                                  ...       ...
23639  noelle loses a bet to akarsha and it somehow e...   neutral
23640  they call her... weekeeshee...\n#butterflysoup...   neutral
23641  put out what you wanna see more of, amirite ga...   neutral
23642  i don't need anybody, i'm fine here on my own\...   neutral
23643  Selamat Siang sahabat online, nih aku sedikit ...  positive

[23644 rows x 2 columns]

# 6. Integration Data File Tweet Label Sentiment ITE

In [30]:
dataset_label_ite

       sentimen                                              Tweet
0           0.0  barusan liat tulisan di belakang truk rela inj...
1           0.0  her itu lho miss kevin sama keven rebutan gimb...
2           0.0    iya rep gatau aku masih kelas 4 sd ehh di block
3           0.0    aku mohon tepatilah janjimu penantiancintaeps19
4           0.0  bukan beria nk kahwin sbb gatal celah kangkang...
...         ...                                                ...
12642       6.0  Jangan dibahas dong, udah paham aja kan di kau...
12643       6.0  di agama lo nyembah nya siapa sih? masa Tuhan ...
12644       6.0  Katanya demi kemanusiaan, kemanusiaan milik ma...
12645       6.0         Orang timur kurang pintar dari orang barat
12646       6.0  Penistaan agama, Yesus Tuhan kok disalib sih k...

[12647 rows x 2 columns]

In [31]:
# rename column 

dataset_label_ite = dataset_label_ite[['Tweet','sentimen']].rename(columns={'Tweet':'Tweet',
                                                                             'sentimen' : 'label'})
dataset_label_ite

                                                   Tweet  label
0      barusan liat tulisan di belakang truk rela inj...    0.0
1      her itu lho miss kevin sama keven rebutan gimb...    0.0
2        iya rep gatau aku masih kelas 4 sd ehh di block    0.0
3        aku mohon tepatilah janjimu penantiancintaeps19    0.0
4      bukan beria nk kahwin sbb gatal celah kangkang...    0.0
...                                                  ...    ...
12642  Jangan dibahas dong, udah paham aja kan di kau...    6.0
12643  di agama lo nyembah nya siapa sih? masa Tuhan ...    6.0
12644  Katanya demi kemanusiaan, kemanusiaan milik ma...    6.0
12645         Orang timur kurang pintar dari orang barat    6.0
12646  Penistaan agama, Yesus Tuhan kok disalib sih k...    6.0

[12647 rows x 2 columns]

In [32]:
# count label
dataset_label_ite['label'].value_counts()

label
0.0    5327
2.0    4188
1.0    2792
4.0     152
6.0     100
3.0      58
5.0      29
Name: count, dtype: int64

In [33]:
# mapping number score label sentiment to text label sentiment

number_to_sentiment_ite = {
    0.0: 'neutral',
    2.0: 'negative',
    1.0: 'positive',
}

# change number score label sentiment to text label sentiment

dataset_label_ite['label'] = dataset_label_ite['label'].map(number_to_sentiment_ite)
dataset_label_ite

                                                   Tweet    label
0      barusan liat tulisan di belakang truk rela inj...  neutral
1      her itu lho miss kevin sama keven rebutan gimb...  neutral
2        iya rep gatau aku masih kelas 4 sd ehh di block  neutral
3        aku mohon tepatilah janjimu penantiancintaeps19  neutral
4      bukan beria nk kahwin sbb gatal celah kangkang...  neutral
...                                                  ...      ...
12642  Jangan dibahas dong, udah paham aja kan di kau...      NaN
12643  di agama lo nyembah nya siapa sih? masa Tuhan ...      NaN
12644  Katanya demi kemanusiaan, kemanusiaan milik ma...      NaN
12645         Orang timur kurang pintar dari orang barat      NaN
12646  Penistaan agama, Yesus Tuhan kok disalib sih k...      NaN

[12647 rows x 2 columns]

In [34]:
# check missing value

dataset_label_ite.isnull().sum()

Tweet      0
label    340
dtype: int64

In [35]:
# delete row missing value (NaN)
dataset_label_ite = dataset_label_ite.dropna(subset=['Tweet', 'label'])

# Kadang data tidak NaN, tapi isinya cuma spasi setelah dibersihkan
dataset_label_ite = dataset_label_ite[dataset_label_ite['label'].str.strip() != '']

# Agar urutan baris kembali rapi (0, 1, 2, ...) tanpa ada angka yang melompat
dataset_label_ite = dataset_label_ite.reset_index(drop=True)

dataset_label_ite

                                                   Tweet     label
0      barusan liat tulisan di belakang truk rela inj...   neutral
1      her itu lho miss kevin sama keven rebutan gimb...   neutral
2        iya rep gatau aku masih kelas 4 sd ehh di block   neutral
3        aku mohon tepatilah janjimu penantiancintaeps19   neutral
4      bukan beria nk kahwin sbb gatal celah kangkang...   neutral
...                                                  ...       ...
12302            tp gue gak ngerti sh maksudnya apa wkwk  negative
12303  aku ingatkan gagal tadbir negara dengan elok j...  negative
12304  kalo kamu lagi dimana mana dan itu bukan daera...  negative
12305  biasalah tu perempuan kena berjaga jaga muka m...  negative
12306  terkadang kamu perlu membentang jarak agar tau...  negative

[12307 rows x 2 columns]

In [36]:
# count label
dataset_label_ite['label'].value_counts()

label
neutral     5327
negative    4188
positive    2792
Name: count, dtype: int64

In [37]:
# check missing value

dataset_label_ite.isnull().sum()

Tweet    0
label    0
dtype: int64

# 7. Integration Data File Sentiment Comment Youtube

In [38]:
dataset_youtube_comment

,video_id,author,comment,label,Unnamed: 4
0,g_fkq6WHcOs,@DesiCahaya-c7r,Gambar kebaretnya boongan ternyata,0.0,0 = negatif
1,g_fkq6WHcOs,@CelineElviraNatalia,"Buat pemakai biasa sama saja iphone 16 promax,...",0.0,1 = netral
2,g_fkq6WHcOs,@borisdominggo,Case “poco&quot; 😂,1.0,2 = positif
3,g_fkq6WHcOs,@noname-jb4rz,Kaum miFans dan kaum munafik iri dengki lg kum...,0.0,NaN
4,g_fkq6WHcOs,@SIAPA-e8b,Saya mah nunggu S26 Ultra aja,0.0,NaN
...,...,...,...,...,...
4197,9-poYwCZxDQ,@ach.fahrurrozi,Waw amazing,NaN,NaN
4198,9-poYwCZxDQ,@muhammadauliarifan9635,halo banh,NaN,NaN
4199,9-poYwCZxDQ,@rizkiokta3404,pagi pagi bener nii,NaN,NaN
4200,9-poYwCZxDQ,@musthofa7104,Wihh,NaN,NaN
4201,9-poYwCZxDQ,@Sebastianverstappen,Ke - 5 nih,NaN,NaN

In [40]:
# rename column 

dataset_youtube_comment = dataset_youtube_comment[['comment','label']].rename(columns={'comment':'Tweet',
                                                                             'label' : 'label'})
dataset_youtube_comment

                                                  Tweet  label
0                    Gambar kebaretnya boongan ternyata    0.0
1     Buat pemakai biasa sama saja iphone 16 promax,...    0.0
2                                    Case “poco&quot; 😂    1.0
3     Kaum miFans dan kaum munafik iri dengki lg kum...    0.0
4                         Saya mah nunggu S26 Ultra aja    0.0
...                                                 ...    ...
4197                                        Waw amazing    NaN
4198                                          halo banh    NaN
4199                                pagi pagi bener nii    NaN
4200                                               Wihh    NaN
4201                                         Ke - 5 nih    NaN

[4202 rows x 2 columns]

In [41]:
# count label
dataset_youtube_comment['label'].value_counts()

label
1.0    304
0.0    173
2.0     63
Name: count, dtype: int64

In [42]:
# mapping number score label sentiment to text label sentiment

number_to_sentiment_youtube_comment = {
    0.0: 'negative',
    2.0: 'positive',
    1.0: 'neutral',
}

# change number score label sentiment to text label sentiment

dataset_youtube_comment['label'] = dataset_youtube_comment['label'].map(number_to_sentiment_youtube_comment)
dataset_youtube_comment

                                                  Tweet     label
0                    Gambar kebaretnya boongan ternyata  negative
1     Buat pemakai biasa sama saja iphone 16 promax,...  negative
2                                    Case “poco&quot; 😂   neutral
3     Kaum miFans dan kaum munafik iri dengki lg kum...  negative
4                         Saya mah nunggu S26 Ultra aja  negative
...                                                 ...       ...
4197                                        Waw amazing       NaN
4198                                          halo banh       NaN
4199                                pagi pagi bener nii       NaN
4200                                               Wihh       NaN
4201                                         Ke - 5 nih       NaN

[4202 rows x 2 columns]

In [43]:
# check missing value

dataset_youtube_comment.isnull().sum()

Tweet       0
label    3662
dtype: int64

In [44]:
# delete row missing value (NaN)
dataset_youtube_comment = dataset_youtube_comment.dropna(subset=['Tweet', 'label'])

# Kadang data tidak NaN, tapi isinya cuma spasi setelah dibersihkan
dataset_youtube_comment = dataset_youtube_comment[dataset_youtube_comment['label'].str.strip() != '']

# Agar urutan baris kembali rapi (0, 1, 2, ...) tanpa ada angka yang melompat
dataset_youtube_comment = dataset_youtube_comment.reset_index(drop=True)

dataset_youtube_comment

                                                 Tweet     label
0                   Gambar kebaretnya boongan ternyata  negative
1    Buat pemakai biasa sama saja iphone 16 promax,...  negative
2                                   Case “poco&quot; 😂   neutral
3    Kaum miFans dan kaum munafik iri dengki lg kum...  negative
4                        Saya mah nunggu S26 Ultra aja  negative
..                                                 ...       ...
535  Mungkin cina jawab dengan xiaomi 17 pro max. M...  negative
536  Kalo bisa bikin power management bagus di hp d...   neutral
537  Makin kesini makin sadar ya klo indonesia ga b...  negative
538                Nonton ini pake realme lcd retak2..   neutral
539  Terimakasih Om Helmi Yahya yg udah undang &quo...  positive

[540 rows x 2 columns]

In [45]:
# check missing value

dataset_youtube_comment.isnull().sum()

Tweet    0
label    0
dtype: int64

In [46]:
# count label
dataset_youtube_comment['label'].value_counts()

label
neutral     304
negative    173
positive     63
Name: count, dtype: int64

# 8. Integration Data File Label Sentiment Netizen Indonesia Twitter

In [47]:
dataset_sent_net_indo

,product_name,review_text,sentiment
0,Basic Online Course Learning (BOCL),"Materinya goks abis, auto paham! Instrukturnya...",2.0
1,Premium Online Learning (POL),"Platformnya anjay, interaktif banget, jadi gak...",2.0
2,Private Online Course Learning (POCL),"Mentornya pro player, ngajarnya santuy tapi ng...",2.0
3,Onsite Course Learning (OCL),"Sumpah, ini kursus paling oke! Ilmunya kepake ...",2.0
4,Private Course Onsite Learning (PCOL),Sertifikatnya nampol buat naikin CV. Vibes bel...,2.0
...,...,...,...
2189,Private Course Onsite Learning (PCOL),"Sertifikatnya dapet, tapi impact-nya belum ker...",1.0
2190,Basic Online Course Learning (BOCL),"Harganya sebanding sama ilmunya. Mantap jiwa, ...",2.0
2191,Premium Online Learning (POL),"CS-nya ampas banget, slow respon, gak solutif....",0.0
2192,Private Online Course Learning (POCL),"Yaah, sesuai harga lah ya. Gak jelek-jelek ama...",1.0
2193,Onsite Course Learning (OCL),Kualitasnya jua,NaN

In [48]:
# rename column 

dataset_sent_net_indo = dataset_sent_net_indo[['review_text','sentiment']].rename(columns={'review_text':'Tweet',
                                                                             'sentiment' : 'label'})
dataset_sent_net_indo

                                                  Tweet  label
0     Materinya goks abis, auto paham! Instrukturnya...    2.0
1     Platformnya anjay, interaktif banget, jadi gak...    2.0
2     Mentornya pro player, ngajarnya santuy tapi ng...    2.0
3     Sumpah, ini kursus paling oke! Ilmunya kepake ...    2.0
4     Sertifikatnya nampol buat naikin CV. Vibes bel...    2.0
...                                                 ...    ...
2189  Sertifikatnya dapet, tapi impact-nya belum ker...    1.0
2190  Harganya sebanding sama ilmunya. Mantap jiwa, ...    2.0
2191  CS-nya ampas banget, slow respon, gak solutif....    0.0
2192  Yaah, sesuai harga lah ya. Gak jelek-jelek ama...    1.0
2193                                    Kualitasnya jua    NaN

[2194 rows x 2 columns]

In [49]:
# count label
dataset_sent_net_indo['label'].value_counts()

label
2.0    1026
0.0     621
1.0     546
Name: count, dtype: int64

In [50]:
# mapping number score label sentiment to text label sentiment

number_to_sentiment_sent_net_indo = {
    0.0: 'negative',
    2.0: 'positive',
    1.0: 'neutral',
}

# change number score label sentiment to text label sentiment

dataset_sent_net_indo['label'] = dataset_sent_net_indo['label'].map(number_to_sentiment_sent_net_indo)
dataset_sent_net_indo

                                                  Tweet     label
0     Materinya goks abis, auto paham! Instrukturnya...  positive
1     Platformnya anjay, interaktif banget, jadi gak...  positive
2     Mentornya pro player, ngajarnya santuy tapi ng...  positive
3     Sumpah, ini kursus paling oke! Ilmunya kepake ...  positive
4     Sertifikatnya nampol buat naikin CV. Vibes bel...  positive
...                                                 ...       ...
2189  Sertifikatnya dapet, tapi impact-nya belum ker...   neutral
2190  Harganya sebanding sama ilmunya. Mantap jiwa, ...  positive
2191  CS-nya ampas banget, slow respon, gak solutif....  negative
2192  Yaah, sesuai harga lah ya. Gak jelek-jelek ama...   neutral
2193                                    Kualitasnya jua       NaN

[2194 rows x 2 columns]

In [51]:
# check missing value

dataset_sent_net_indo.isnull().sum()

Tweet    0
label    1
dtype: int64

In [52]:
# delete row missing value (NaN)
dataset_sent_net_indo = dataset_sent_net_indo.dropna(subset=['Tweet', 'label'])

# Kadang data tidak NaN, tapi isinya cuma spasi setelah dibersihkan
dataset_sent_net_indo = dataset_sent_net_indo[dataset_sent_net_indo['label'].str.strip() != '']

# Agar urutan baris kembali rapi (0, 1, 2, ...) tanpa ada angka yang melompat
dataset_sent_net_indo = dataset_sent_net_indo.reset_index(drop=True)

dataset_sent_net_indo

                                                  Tweet     label
0     Materinya goks abis, auto paham! Instrukturnya...  positive
1     Platformnya anjay, interaktif banget, jadi gak...  positive
2     Mentornya pro player, ngajarnya santuy tapi ng...  positive
3     Sumpah, ini kursus paling oke! Ilmunya kepake ...  positive
4     Sertifikatnya nampol buat naikin CV. Vibes bel...  positive
...                                                 ...       ...
2188  Platformnya oke lah buat operasional, jarang a...   neutral
2189  Sertifikatnya dapet, tapi impact-nya belum ker...   neutral
2190  Harganya sebanding sama ilmunya. Mantap jiwa, ...  positive
2191  CS-nya ampas banget, slow respon, gak solutif....  negative
2192  Yaah, sesuai harga lah ya. Gak jelek-jelek ama...   neutral

[2193 rows x 2 columns]

In [53]:
# check missing value

dataset_sent_net_indo.isnull().sum()

Tweet    0
label    0
dtype: int64

In [54]:
# count label
dataset_sent_net_indo['label'].value_counts()

label
positive    1026
negative     621
neutral      546
Name: count, dtype: int64

# 9. Integration Dataset Sentiment Label Review Startup Indonesia

In [55]:
dataset_review_startup

           label                                              Tweet
0       negative  Harga harga di Blibli cenderung di atas orange...
1       negative  Platform e-commerce yang menurut saya belum pa...
2       negative  Sudah setahuan belakang ini pelayanan pengirim...
3       positive  Pengen mencoba berbelanja tapi gak jadi karena...
4       negative  Tidak jadi gw rating bintang 5 . Applikasi pen...
...          ...                                                ...
841659  negative                                                  👻
841660  negative                                           😈😈😈😈😈😈😈😈
841661  negative                                          👍👍👍👍👍👍👍👍👍
841662  negative                                                 😊😊
841663  negative                                         First?????

[841664 rows x 2 columns]

In [56]:
# rename column 

dataset_review_startup = dataset_review_startup[['Tweet','label']]
dataset_review_startup

                                                    Tweet     label
0       Harga harga di Blibli cenderung di atas orange...  negative
1       Platform e-commerce yang menurut saya belum pa...  negative
2       Sudah setahuan belakang ini pelayanan pengirim...  negative
3       Pengen mencoba berbelanja tapi gak jadi karena...  positive
4       Tidak jadi gw rating bintang 5 . Applikasi pen...  negative
...                                                   ...       ...
841659                                                  👻  negative
841660                                           😈😈😈😈😈😈😈😈  negative
841661                                          👍👍👍👍👍👍👍👍👍  negative
841662                                                 😊😊  negative
841663                                         First?????  negative

[841664 rows x 2 columns]

In [58]:
# check missing value

dataset_review_startup.isnull().sum()

Tweet    0
label    0
dtype: int64

In [59]:
# count label
dataset_review_startup['label'].value_counts()

label
positive    504464
negative    280465
neutral      56735
Name: count, dtype: int64

# Merge DataFrame 1, 2, 3, 4, 5

In [60]:
# merge dataframe 

dataset_training = pd.concat([dataset_tweet_emotion, dataset_keyword_banjir, dataset_keyword_jokowi, dataset_pilpres, dataset_ppkm, 
                              dataset_label_ite, dataset_youtube_comment, dataset_sent_net_indo, dataset_review_startup], ignore_index=True)
dataset_training

                                                    Tweet     label
0       Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...  negative
1       Sesama cewe lho (kayaknya), harusnya bisa lebi...  negative
2       Kepingin gudeg mbarek Bu hj. Amad Foto dari go...  positive
3       Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...  negative
4       Sharing pengalaman aja, kemarin jam 18.00 bata...  positive
...                                                   ...       ...
915718                                                  👻  negative
915719                                           😈😈😈😈😈😈😈😈  negative
915720                                          👍👍👍👍👍👍👍👍👍  negative
915721                                                 😊😊  negative
915722                                         First?????  negative

[915723 rows x 2 columns]

In [61]:
# count label
dataset_training['label'].value_counts()

label
positive    534024
negative    300745
neutral      80950
Name: count, dtype: int64

In [62]:
# check missing value

dataset_training.isnull().sum()

Tweet    0
label    4
dtype: int64

In [63]:
# delete row missing value (NaN)
dataset_training = dataset_training.dropna(subset=['Tweet', 'label'])

# Kadang data tidak NaN, tapi isinya cuma spasi setelah dibersihkan
dataset_training = dataset_training[dataset_training['Tweet'].str.strip() != '']

# Agar urutan baris kembali rapi (0, 1, 2, ...) tanpa ada angka yang melompat
dataset_training = dataset_training.reset_index(drop=True)

dataset_training

                                                    Tweet     label
0       Soal jln Jatibaru,polisi tdk bs GERTAK gubernu...  negative
1       Sesama cewe lho (kayaknya), harusnya bisa lebi...  negative
2       Kepingin gudeg mbarek Bu hj. Amad Foto dari go...  positive
3       Jln Jatibaru,bagian dari wilayah Tn Abang.Peng...  negative
4       Sharing pengalaman aja, kemarin jam 18.00 bata...  positive
...                                                   ...       ...
915714                                                  👻  negative
915715                                           😈😈😈😈😈😈😈😈  negative
915716                                          👍👍👍👍👍👍👍👍👍  negative
915717                                                 😊😊  negative
915718                                         First?????  negative

[915719 rows x 2 columns]

In [64]:
# check missing value

dataset_training.isnull().sum()

Tweet    0
label    0
dtype: int64

In [65]:
# count label
dataset_training['label'].value_counts()

label
positive    534024
negative    300745
neutral      80950
Name: count, dtype: int64

# Save DataFrame dataset_training to CSV

In [66]:
dataset_training.to_csv('dataset_training.csv', index=False)